<?php

$phrases = array("Câlins \o/",
"Bisous \o/",
"Câlin !",
"Bisou !",
"Câlin ♥",
"Bisou ♥",
"Câlin surprise ♥",
"Vous reprendrez bien un peu de pipou n'est-ce pas ? Voilà pour vous : Câlin ♥",
"Trop de pipou ne tue pas le pipou : Câlin ♥",
"Câlin : n.m. Câlinerie, tendresse, douceur affectueuse, étreinte affectueuse (pour toi). ♥",
"Notre serveur a détecté une carence en pipou, procédure de réparation : Câlin ♥",
"Il était une fois un bot automatique qui répandait le pipou, et pouf : Câlin ♥",
"Bonjour, auriez-vous quelques minutes à m'accorder pour parler de notre Seigneur Pipou ? Câlin ♥",
"Nous avons un projet fou : dominer le monde par la force du pipou. Première étape : Câlin ♥",
"Bonjour, bienvenue à bord de la compagnie PipouAirlines, attachez votre ceinture : Câlin ♥",
"Notre service après-vente pipou est ravi de vous offrir la compensation suivante : Câlin ♥",
"Cher utilisateur, pour votre fidélité, un câlin vous est offert par la maison ! Câlin ♥",
"Un jour, le pipou dominera le monde, en attendant : Câlin ♥",
"Some men just want to watch the world pipou : Câlin ♥",
"Il y a deux sortes de personnes sur terre : les pipous et les autres. Câlin ♥",
"Être pipou ou ne pas être pipou, ce n'est pas la question : Câlin ♥",
"Je pense donc je suis pipou : Câlin ♥",
"Deux choses sont infinies : l'Univers et le pipou. Câlin ♥",
"Encore une mission pour pipou-man ! Câlin-laser activé ! Câlin envoyé !",
"Vous avez reçu un colis pipou à votre nom : Câlin ♥",
"Démarrage - Initialisation du module pipou - Envoi du message pipou : CÂLIN ♥",
"Message pipou - STOP - Urgent - STOP - Voici - STOP - Câlin ♥",
"Ceci est un message d'une grande importance, veuillez transmettre : Câlin ♥",
"Explosion de câlins ♥",
"Et paf ! Un câlin ! ♥",
"!!! Un pipou sauvage apparaît ! Pipou sauvage attaque Câlin ! C'est super efficace !",
"Et pouf ! Un câlin ! ♥",
"Tour de magie pipou : ... Tadaaa ! Un câlin ! ♥",
"Bravo ! Tu as gagné une visite gratuite dans la pipouterie ! Câlin ! ♥",
"Vous êtes le 1.000.000.000ème visiteur sur notre site pipou ! Vous avez gagné un câlin ! ♥",
"Des rencontres pipou dans ta région : envoie rien du tout, reçois juste ce câlin. ♥",
"Alo ui cer pipou : Câlin ♥",
"La réponse à la grande question sur la vie, l'univers et le reste ? Câlin ♥",
"Vous avez un message pipou en attente : Câlin ♥",
"Il a un réservoir de pipou illimité !!! Les non-pipous le détestent !!! Câlin !!!",
"All you need is pipou ! Pipou is all you need ! Câlin ! ♥",
"Imagine all the people, living life in pipou ! Wouhouhou ! Câlin ! ♥",
"Pipou un jour, pipou toujours ! Câlin ♥",
"Attaque de câlins ♥",
"Pipou partout, câlins partout ♥",
"Les power-pipou sont tous rassemblés, formation Méga-Pipou ! Câlin ♥",
"Un litre de pipou, une cuillère à soupe de tendresse, un zeste de bisou et voilà : Câlin ♥",
"It's dangerous to go alone, take this : Câlin ♥",
"Livraison gratuite et immédiate : câlin ♥",
"Des bisous, des bisous, encore des bisous !",
"Un câlin pour tous ! Tous pour un câlin ! ♥",
"The night is dark and full of terrors, take this : câlin ♥",
"Je chante le pipou, je danse le pipou, je ne suis qu'amour ! Câlin ♥",
"Un seul pipou nous manque et tout est dépeuplé : câlin ♥",
"Ce bot a pris toutes les étoiles du ciel pour les mettre dans ses tweets : câlin ♥",
"Le pipou c'est comme une boîte de chocolat, on ne sait jamais sur quoi on va tomber : câlin ♥",
"Le pipou c'est comme une boîte de chocolat, on ne sait jamais sur quoi on va tomber : bisou ♥",
"Tout ce que je sais, c'est que le pipou c'est bien : câlin ♥",
"Que nul n'entre s'il n'est pipou : câlin ♥",
"Le pipou a ses raisons que la raison ignore : câlin ♥",
"Capitaine Pipou au rapport : Câlin ♥",
"Pipou's not dead ! Câlin ♥",
"Météo pipou du jour : risque d'avalanche de câlin imminente ! Câlins ♥");

$phrasesForMentions = array("Câlins \o/",
"Bisous \o/",
"Câlin !",
"Bisou !",
"Câlin ♥",
"Bisou ♥",
"Oh, j'ai cru voir une demande de pipou : câlin ♥",
"Oh, j'ai cru voir un besoin de pipou : câlin !",
"Livraison gratuite et immédiate : câlin ♥",
"Des bisous, des bisous, encore des bisous !",
"Deux choses sont infinies : l'Univers et le pipou. Câlin ♥",
"Encore une mission pour pipou-man ! Câlin-laser activé ! Câlin envoyé !",
"Vous avez reçu un colis pipou à votre nom : Câlin ♥",
"Démarrage - Initialisation du module pipou - Envoi du message pipou : CÂLIN !",
"Message pipou - STOP - Urgent - STOP - Voici - STOP - Câlin !",
"Ceci est un message d'une grande importance, veuillez transmettre : Câlin ♥",
"Explosion de câlins ♥",
"Et paf ! Un câlin ! ♥",
"!!! Un pipou sauvage apparaît ! Pipou sauvage attaque Câlin ♥ ! C'est super efficace !",
"Et pouf ! Un câlin ! ♥",
"Tour de magie pipou : ... Tadaaa ! Un câlin ! ♥",
"Bravo ! Tu as gagné une visite gratuite dans la pipouterie ! Câlin ! ♥",
"Pipou un jour, pipou toujours ! Câlin ♥",
"Attaque de câlins ♥",
"Pipou partout, câlins partout ♥",
"Les power-pipou sont tous rassemblés, formation Méga-Pipou ! Câlin ! ♥",
"Les câlins, on en a tous besoin : CÂLIN ♥",
"Un câlin pour tous ! Tous pour un câlin ! ♥",
"It's dangerous to go alone, take this : Câlin ♥",
"The night is dark and full of terrors, take this : câlin ♥",
"Je chante le pipou, je danse le pipou, je ne suis qu'amour ! Câlin ♥",
"Un seul pipou nous manque et tout est dépeuplé : câlin ♥",
"Ce bot a pris toutes les étoiles du ciel pour les mettre dans ses tweets : câlin ♥",
"Le pipou c'est comme une boîte de chocolat, on ne sait jamais sur quoi on va tomber : câlin ♥",
"Le pipou c'est comme une boîte de chocolat, on ne sait jamais sur quoi on va tomber : bisou ♥",
"Tout ce que je sais, c'est que le pipou c'est bien : câlin ♥",
"Que nul n'entre s'il n'est pipou : câlin ♥",
"Le pipou a ses raisons que la raison ignore : câlin ♥",
"Capitaine Pipou au rapport : Câlin ♥",
"Pipou's not dead ! Câlin ♥",
"Toujours au poste pour offrir un câlin aux nécessiteux ! Câlin ♥");

?>
