<?php

$phrases = array("Câlins \o/",
"Bisous \o/",
"Câlin",
"Bisou",
"Câlin surprise !",
"Vous reprendrez bien un peu de pipou n'est-ce pas ? Voilà pour vous : Câlin !",
"Trop de pipou ne tue pas le pipou : Câlin !",
"Câlin : n.m. Câlinerie, tendresse, douceur affectueuse, étreinte affectueuse. Et voilà
Notre serveur a détecté une carence en pipou, procédure de réparation : Câlin !",
"Il était une fois un bot automatique qui répandait le pipou, et pouf : Câlin !",
"Bonjour, auriez-vous quelques minutes à m'accorder pour parler de notre Seigneur Pipou ? Câlin !",
"Nous avons un projet fou : dominer le monde par la force du pipou. Première étape : Câlin.",
"Bonjour, bienvenue à bord de la compagnie PipouAirlines, attachez votre ceinture : Câlin !",
"Notre service après-vente pipou est ravi de vous offrir la compensation suivante : Câlin.",
"Cher utilisateur, pour votre fidélité, un câlin vous est offert par la maison ! Câlin !",
"Un jour, le pipou dominera le monde, en attendant : Câlin.",
"Some men just want to watch the world pipou : Câlin.",
"Il y a deux sortes de personnes sur terre : les pipous et les autres. Câlin !",
"Être pipou ou ne pas être pipou, ce n'est pas la question : Câlin.",
"Je pense donc je suis pipou : Câlin.",
"Deux choses sont infinies : l'Univers et le pipou. Câlin !",
"Encore une mission pour pipou-man ! Câlin-laser activé ! Câlin envoyé !",
"Vous avez reçu un colis pipou à votre nom : Câlin !",
"Démarrage - Initialisation du module pipou - Envoi du message pipou : CÂLIN !",
"Message pipou - STOP - Urgent - STOP - Voici - STOP - Câlin !",
"Ceci est un message d'une grande importance, veuillez transmettre : Câlin.",
"Explosion de câlins !",
"Et paf ! Un câlin !",
"!!! Un pipou sauvage apparaît ! Pipou sauvage attaque Câlin ! C'est super efficace !",
"Et pouf ! Un câlin !",
"Tour de magie pipou : ... Tadaaa ! Un câlin !",
"Bravo ! Tu as gagné une visite gratuite dans la pipouterie ! Câlin !",
"Vous êtes le 1.000.000.000ème visiteur sur notre site pipou ! Vous avez gagné un câlin !",
"Des rencontres pipou dans ta région : envoie rien du tout, reçois juste ce câlin.",
"Alo ui cer pipou : Câlin !",
"La réponse à la grande question sur la vie, l'univers et le reste ? Câlin.",
"Vous avez un message pipou en attente : Câlin.",
"Il a un réservoir de pipou illimité !!! Les non-pipous le détestent !!! Câlin !!!",
"All you need is pipou ! Pipou is all you need ! Câlin !",
"Imagine all the people, living life in pipou ! Wouhouhou ! Câlin !",
"Pipou un jour, pipou toujours ! Câlin !",
"Attaque de câlins !",
"Pipou partout, câlins partout !",
"Les power-pipou sont tous rassemblés, formation Méga-Pipou ! Câlin !",
"Un litre de pipou, une cuillère à soupe de tendresse, un zeste de bisou et voilà : Câlin !",
"It's dangerous to go alone, take this : Câlin !",
"Météo pipou du jour : risque d'avalanche de câlin imminente ! Câlins !");

?>
